build:
  nodes:
    analysis:
      tests:
        override:
          - phpcs-run
          - php-scrutinizer-run
    my-tests:
      environment:
        php:
          version: 7.4
      # tests:
      #   override:
      #     - command: composer app:test
      #       coverage:
      #         file: clover.xml
      #         format: php-clover
